# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Accordion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Accordion
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end
